### ISSUE TITLE
Visonic Powerlink 3

### ISSUE THREAD

**Issue by githubpreny** [Froggy-AA/visonic-powerlink3-api#1]
Bonjour froggy,

Je re-créé un **[fil](https://community.jeedom.com/t/powerlink-3-alarme-visonic/23732)** de messages dans le nouveau forum Jeedom, relatif à ce sujet. J'espère que tu pourras venir donner des nouvelles de ton installation ...

Cordialement,
F4F

**Comment by Froggy-AA** [comment]
Infos tracée
