### ISSUE TITLE
which units do library this support?

### ISSUE THREAD

**Issue by mapa0402** [Froggy-AA/visonic-powerlink3-api#2]
Hi, awesome work,
would this by any chance work with visonic powermax 360r?

**Comment by Froggy-AA** [comment]
Thank you.

I don't know. This API is not documented by visonic. I think it works with the powerink v3 module but I'm not sure. 
The best think to do is to try to access http://alarm_ip:8181/ with your internet navigator. If you have a return, it can work. If no result, try to activate the domitic module on your alarm and retry.

**Comment by mapa0402** [comment]
ok, I dont get return on the ip, but I have mobile-app that can control.
What is that domitic module that needs activation?

**Comment by Froggy-AA** [comment]
I dont't remember the name, I have to check. 
The app uses the internet connection wich is different to the JSON RPC api.
